### ISSUE TITLE
Last develop upgrade.php error

### ISSUE THREAD

**Issue by stefaweb** [mailwatch/MailWatch#838]
Seems the last upgrade.php do not like to be run 2 times.

```
 - Fix schema for last_update field in `maillog` table................PHP Fatal error:  Uncaught exception 'mysqli_sql_exception' with message 'Duplicate column name 'last_update'' in /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php:82
Stack trace:
#0 /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php(82): mysqli->query('ALTER TABLE `ma...')
#1 /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php(434): executeQuery('ALTER TABLE `ma...')
#2 {main}
  thrown in /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php on line 82

Fatal error: Uncaught exception 'mysqli_sql_exception' with message 'Duplicate column name 'last_update'' in /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php:82
Stack trace:
#0 /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php(82): mysqli->query('ALTER TABLE `ma...')
#1 /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php(434): executeQuery('ALTER TABLE `ma...')
#2 {main}
  thrown in /home/xxxxx/mailwatch-1.2.4-dev/upgrade.php on line 82
```

**Comment by stefaweb** [comment]
Done.
